name: template_codes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  http: ^1.2.1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  change_app_package_name: ^1.1.0
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  sqflite: ^2.3.3+1
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.0
  path_provider: ^2.1.3
  flutter_timezone: ^1.0.4
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  fluttertoast: ^8.2.5
  adaptive_theme: ^3.6.0
  pinput: ^4.0.0
  local_auth: ^2.2.0
  mask_text_input_formatter: ^2.9.0
  carousel_slider: ^4.2.1
  lottie: ^3.1.1
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  dotted_border: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  location: ^5.0.3
  easy_localization: ^3.0.6
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pdf: ^3.10.8
  flutter_pdfview: ^1.2.7
  printing: ^5.12.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sql/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Black.ttf
         - asset: assets/fonts/Poppins/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
         - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
         - asset: assets/fonts/Poppins/Poppins-Light.ttf
         - asset: assets/fonts/Poppins/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins/Poppins-Thin.ttf

